openapi: 3.0.0
info:
  title: 'API de Minteck Projects CMS'
  version: '1.0'
paths:
  /api/public/info/page.php:
    get:
      parameters:
        -
          name: id
          in: query
          description: 'Identifiant de la page'
          required: true
          schema:
            type: string
            example: index
      responses:
        '200':
          description: 'Informations concernant une page'
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/InfoPage'
              example:
                size: 22369368
                sizestr: 21.333M
        '401':
          description: 'API désactivé par l''administrateur du site'
        '500':
          description: 'Erreur interne de l''API'
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/Error'
              example:
                error: 420
                message: 'Required argument is undefined'
  /api/public/info/size.php:
    get:
      responses:
        '200':
          description: 'Taille des fichiers du site dans différents formats'
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/InfoSize'
              example:
                size: 22369368
                sizestr: 21.333M
        '401':
          description: 'API désactivé par l''administrateur du site'
        '500':
          description: 'Erreur interne de l''API'
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/Error'
              example:
                error: 420
                message: 'Required argument is undefined'
components:
  schemas:
    Error:
      properties:
        error:
          description: 'Nom interne de l''erreur, ou E_INTERNAL si l''erreur est inconnue'
          type: string
          example: E_ARG_MISSING
        message:
          description: 'Court message (en anglais) associé à l''erreur'
          type: string
          example: 'Required argument is undefined'
      type: object
    InfoPage:
      properties:
        id:
          description: 'Identifiant de la page'
          type: string
          example: index
        title:
          description: 'Titre de la page'
          type: string
          example: Accueil
        size:
          description: 'Taille de la page (en octets)'
          type: integer
          example: '421'
          nullable: true
        path:
          description: 'Emplacement de la page par rapport à la racine du site'
          type: string
          example: /
        hidden:
          description: 'Page masquée depuis les paramètres avancés'
          type: boolean
          example: 'false'
      type: object
    InfoSize:
      properties:
        size:
          description: 'Taille du site en octets'
          type: integer
          example: '22369368'
        sizestr:
          description: 'Taille du site dans un format plus lisible'
          type: string
          example: 21.333M
      type: object
