// $('document').ready(() => {
//     try {document.querySelector('img[src="/resources/image/admin_logout.png"]').src = "/resources/image/classic_admin_logout.png";} catch (err) {}
//     try {document.querySelector('img[src="/resources/image/admin_advanced.png"]').src = "/resources/image/classic_admin_advanced.png";} catch (err) {}
//     try {document.querySelector('img[src="/resources/image/admin_appearance.png"]').src = "/resources/image/classic_admin_appearance.png";} catch (err) {}
//     try {document.querySelector('img[src="/resources/image/admin_calendar.png"]').src = "/resources/image/classic_admin_calendar.png";} catch (err) {}
//     try {document.querySelector('img[src="/resources/image/admin_docs.png"]').src = "/resources/image/classic_admin_docs.png";} catch (err) {}
//     try {document.querySelector('img[src="/resources/image/admin_galery.png"]').src = "/resources/image/classic_admin_galery.png";} catch (err) {}
//     try {document.querySelector('img[src="/resources/image/admin_housekeeping.png"]').src = "/resources/image/classic_admin_housekeeping.png";} catch (err) {}
//     try {document.querySelector('img[src="/resources/image/admin_logout.png"]').src = "/resources/image/classic_admin_logout.png";} catch (err) {}
//     try {document.querySelector('img[src="/resources/image/admin_logs.png"]').src = "/resources/image/classic_admin_logs.png";} catch (err) {}
//     try {document.querySelector('img[src="/resources/image/admin_pages.png"]').src = "/resources/image/classic_admin_pages.png";} catch (err) {}
//     try {document.querySelector('img[src="/resources/image/admin_plugins.png"]').src = "/resources/image/classic_admin_plugins.png";} catch (err) {}
//     try {document.querySelector('img[src="/resources/image/admin_security.png"]').src = "/resources/image/classic_admin_security.png";} catch (err) {}
//     try {document.querySelector('img[src="/resources/image/admin_tosite.png"]').src = "/resources/image/classic_admin_tosite.png";} catch (err) {}
//     try {document.querySelector('img[src="/resources/image/admin_ui.png"]').src = "/resources/image/classic_admin_ui.png";} catch (err) {}
//     try {document.querySelector('img[src="/resources/image/admin_updates.png"]').src = "/resources/image/classic_admin_updates.png";} catch (err) {}
//     try {document.querySelector('img[src="/resources/image/admin_store.png"]').src = "/resources/image/classic_admin_store.png";} catch (err) {}
//     try {document.querySelector('img[src="/resources/image/admin_semantic.png"]').src = "/resources/image/classic_admin_semantic.png";} catch (err) {}
//     try {document.querySelector('img[src="/resources/image/admin.svg"]').src = "/resources/image/classic_admin.svg";} catch (err) {}
//     try {document.querySelector('img[src="/resources/image/contact_address.svg"]').src = "/resources/image/classic_contact_address.svg";} catch (err) {}
//     try {document.querySelector('img[src="/resources/image/contact_email.svg"]').src = "/resources/image/classic_contact_email.svg";} catch (err) {}
//     try {document.querySelector('img[src="/resources/image/contact_phone.svg"]').src = "/resources/image/classic_contact_phone.svg";} catch (err) {}
//     try {document.querySelector('img[src="/resources/image/contact_priority.svg"]').src = "/resources/image/classic_contact_priority.svg";} catch (err) {}
//     try {document.querySelector('img[src="/resources/image/config_file_import.svg"]').src = "/resources/image/classic_config_file_import.svg";} catch (err) {}
//     try {document.querySelector('img[src="/resources/image/config_file_replace.svg"]').src = "/resources/image/classic_config_file_replace.svg";} catch (err) {}
//     try {document.querySelector('img[src="/resources/image/menu.svg"]').src = "/resources/image/classic_menu.svg";} catch (err) {}
//     try {document.querySelector('img[src="/resources/image/tools.svg"]').src = "/resources/image/classic_tools.svg";} catch (err) {}
//     try {document.querySelector('img[src="/resources/image/stats.png"]').src = "/resources/image/classic_stats.png";} catch (err) {}
//     try {document.querySelector('img[src="/resources/image/display.png"]').src = "/resources/image/classic_display.png";} catch (err) {}
//     try {document.querySelector('img[src="/resources/image/display.svg"]').src = "/resources/image/classic_display.svg";} catch (err) {}
//     try {document.querySelector('img[src="/resources/image/rightclick_admin.svg"]').src = "/resources/image/classic_rightclick_admin.svg";} catch (err) {}
//     try {document.querySelector('img[src="/resources/image/rightclick_details.svg"]').src = "/resources/image/classic_rightclick_details.svg";} catch (err) {}
//     try {document.querySelector('img[src="/resources/image/rightclick_exit.svg"]').src = "/resources/image/classic_rightclick_exit.svg";} catch (err) {}
//     try {document.querySelector('img[src="/resources/image/rightclick_home.svg"]').src = "/resources/image/classic_rightclick_home.svg";} catch (err) {}
//     try {document.querySelector('img[src="/resources/image/rightclick_page.svg"]').src = "/resources/image/classic_rightclick_page.svg";} catch (err) {}
//     try {document.querySelector('img[src="/resources/image/rightclick_store.svg"]').src = "/resources/image/classic_rightclick_store.svg";} catch (err) {}
//     try {document.querySelector('img[src="/resources/image/close.svg"]').src = "/resources/image/classic_close.svg";} catch (err) {}
//     try {document.querySelector('img[src="/resources/image/classic_store_verified.svg"]').src = "/resources/image/classic_store_verified.svg";} catch (err) {}
// })