$('document').ready(() => {
    try {document.querySelector('img[src="/resources/image/admin_logout.png"]').src = "/resources/image/suru_admin_logout.png";} catch (err) {}
    try {document.querySelector('img[src="/resources/image/admin_advanced.png"]').src = "/resources/image/suru_admin_advanced.png";} catch (err) {}
    try {document.querySelector('img[src="/resources/image/admin_appearance.png"]').src = "/resources/image/suru_admin_appearance.png";} catch (err) {}
    try {document.querySelector('img[src="/resources/image/admin_calendar.png"]').src = "/resources/image/suru_admin_calendar.png";} catch (err) {}
    try {document.querySelector('img[src="/resources/image/admin_docs.png"]').src = "/resources/image/suru_admin_docs.png";} catch (err) {}
    try {document.querySelector('img[src="/resources/image/admin_galery.png"]').src = "/resources/image/suru_admin_galery.png";} catch (err) {}
    try {document.querySelector('img[src="/resources/image/admin_housekeeping.png"]').src = "/resources/image/suru_admin_housekeeping.png";} catch (err) {}
    try {document.querySelector('img[src="/resources/image/admin_logout.png"]').src = "/resources/image/suru_admin_logout.png";} catch (err) {}
    try {document.querySelector('img[src="/resources/image/admin_logs.png"]').src = "/resources/image/suru_admin_logs.png";} catch (err) {}
    try {document.querySelector('img[src="/resources/image/admin_pages.png"]').src = "/resources/image/suru_admin_pages.png";} catch (err) {}
    try {document.querySelector('img[src="/resources/image/admin_plugins.png"]').src = "/resources/image/suru_admin_plugins.png";} catch (err) {}
    try {document.querySelector('img[src="/resources/image/admin_security.png"]').src = "/resources/image/suru_admin_security.png";} catch (err) {}
    try {document.querySelector('img[src="/resources/image/admin_tosite.png"]').src = "/resources/image/suru_admin_tosite.png";} catch (err) {}
    try {document.querySelector('img[src="/resources/image/admin_ui.png"]').src = "/resources/image/suru_admin_ui.png";} catch (err) {}
    try {document.querySelector('img[src="/resources/image/admin_updates.png"]').src = "/resources/image/suru_admin_updates.png";} catch (err) {}
    try {document.querySelector('img[src="/resources/image/admin_store.png"]').src = "/resources/image/suru_admin_store.png";} catch (err) {}
    try {document.querySelector('img[src="/resources/image/admin_semantic.png"]').src = "/resources/image/suru_admin_semantic.png";} catch (err) {}
    try {document.querySelector('img[src="/resources/image/admin.svg"]').src = "/resources/image/suru_admin.png";} catch (err) {}
    try {document.querySelector('img[src="/resources/image/contact_address.svg"]').src = "/resources/image/suru_contact_address.png";} catch (err) {}
    try {document.querySelector('img[src="/resources/image/contact_email.svg"]').src = "/resources/image/suru_contact_email.png";} catch (err) {}
    try {document.querySelector('img[src="/resources/image/contact_phone.svg"]').src = "/resources/image/suru_contact_phone.png";} catch (err) {}
    try {document.querySelector('img[src="/resources/image/contact_priority.svg"]').src = "/resources/image/suru_contact_priority.png";} catch (err) {}
    try {document.querySelector('img[src="/resources/image/config_file_import.svg"]').src = "/resources/image/suru_file_import.png";} catch (err) {}
    try {document.querySelector('img[src="/resources/image/config_file_replace.svg"]').src = "/resources/image/suru_file_replace.png";} catch (err) {}
    try {document.querySelector('img[src="/resources/image/menu.svg"]').src = "/resources/image/suru_menu.png";} catch (err) {}
    try {document.querySelector('img[src="/resources/image/tools.svg"]').src = "/resources/image/suru_tools.png";} catch (err) {}
    try {document.querySelector('img[src="/resources/image/stats.png"]').src = "/resources/image/suru_stats.png";} catch (err) {}
    try {document.querySelector('img[src="/resources/image/display.png"]').src = "/resources/image/suru_display.png";} catch (err) {}
})